server:
  port: 8083

spring:
  application:
    name: music-service

  datasource:
    url: jdbc:mysql://localhost:3306/revplay_music?createDatabaseIfNotExist=true
    username: root
    password: yourpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: cmV2cGxheV9zdXBlcl9zZWNyZXRfa2V5X2Zvcl9qd3RfMjAyNF92ZXJ5X2xvbmc=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 

feign:
  client:
    config:
      default:
      connectTimeout: 5000
      readTimeout: 5000
circuitbreaker:
  enabled: true