server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: artist-service
          uri: lb://artist-service
          predicates:
            - Path=/api/artists/**

        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/songs/**,/api/albums/**,/api/genres/**

        - id: playlist-service
          uri: lb://playlist-service
          predicates:
            - Path=/api/playlists/**

        - id: favorites-service
          uri: lb://favorites-service
          predicates:
            - Path=/api/favorites/**

        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/api/history/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: cmV2cGxheV9zdXBlcl9zZWNyZXRfa2V5X2Zvcl9qd3RfMjAyNF92ZXJ5X2xvbmc=

logging:
  level:
    org.springframework.cloud.gateway: INFO